name: manual-input
on:
  workflow_dispatch:
    inputs:
      target:
        description: Target
        required: true
        default: dev 
        type: choice
        options:
        - dev
        - dev1
        - dev2 

jobs:
  print-target:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input tag to STDOUT
        run: echo  The target is ${{ github.event.inputs.target }} 
