name: manual-input2
on:
  workflow_dispatch:

jobs:
  print-target:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: yarn

      - run: yarn --version
      
      - run: yarn

