name: manual-input
on:
  workflow_dispatch:

jobs:
  print-target:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print the input tag to STDOUT
        run: echo  The target is hoge
      - run: ls
